# Chroot Terminal — Statik IP (NetworkManager renderer)
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp0s5:
      addresses:
        - 10.211.55.28/24
      routes:
        - to: default
          via: 10.211.55.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      dhcp4: false
